export const platformOptions = [
    'Amazon Prime', 
    'Netflix', 
    'Hulu', 
    'Disney+',
    'Apple TV+',
    'HBO Max',
    'YouTube',
    'Hotstar',
    'Jio Cinema',
    'Other'
  ];
  
  export const genreOptions = [
    'All', 
    'Action', 
    'Adventure',
    'Animation',
    'Biography',
    'Comedy',
    'Crime',
    'Documentary',
    'Drama',
    'Family',
    'Fantasy',
    'Game-Show',
    'History',
    'Horror',
    'Music',
    'Musical',
    'Mystery',
    'News',
    'Reality-TV',
    'Romance',
    'Sci-Fi',
    'Sport',
    'Talk-Show',
    'Thriller',
    'War',
    'Western',
  ];
  